# Generated by Django 4.0.4 on 2023-03-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_line',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_range',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_code',
        ),
    ]
