# Generated by Django 4.0.4 on 2023-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_cloth_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproducts',
            name='color',
        ),
        migrations.AlterField(
            model_name='imageproducts',
            name='image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
