# Generated by Django 4.0.4 on 2023-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionproducts',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
