# Generated by Django 4.0.4 on 2023-03-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_collectionproducts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
