# Generated by Django 4.0.4 on 2023-03-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_post_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='product',
        ),
    ]
